### ISSUE TITLE
Feature Request: "Upcoming Movie" Search by rating

### ISSUE THREAD

**Issue by SageWizdom** [google/sagetv#111]
For the web interface (so I realize this is probably the wrong place) be able to search upcoming movies / recordings by rating (G , PG, etc)  With the ability to select one or more.  (maybe this is a future webserver feature)

**Comment by skiingwiz** [comment]
This will be in the next version of the Web Server plugin.  A pre-release version can be found here: https://forums.sagetv.com/forums/showthread.php?p=607940#post607940

After allowing some time for feedback, this will go into the Sage 9 plugin repository.

**Comment by skiingwiz** [comment]
This was released in version 3.2.1 of the Web UI several days ago.  This issue can be closed.
