### ISSUE TITLE
Feature Request: Web Interface select as And instead of Or

### ISSUE THREAD

**Issue by SageWizdom** [google/sagetv#112]
In the web interface (again, sorry if this is wrong place) when searching, and genre is selected, current behavior is to boolean "OR" the genre selections.  it would be nice to have an option to boolean "AND" the selection.

For example, "Children" and "Animated"

**Comment by skiingwiz** [comment]
This will be in the next version of the Web Server plugin.  A pre-release version can be found here: https://forums.sagetv.com/forums/showthread.php?p=607940#post607940

After allowing some time for feedback, this will go into the Sage 9 plugin repository.

**Comment by skiingwiz** [comment]
This was released in version 3.2.1 of the Web UI several days ago.  This issue can be closed.
