### ISSUE TITLE
Font cropped in .252

### ISSUE THREAD

**Issue by Greg2dot0** [google/sagetv#129]
I installed .252 the other day and now the tops of all the fonts on my HD300 are cropped by 1 or 2 pixels. This isn't limited to the tallest characters, so not sure what's going on. I'm attaching a photo
![img_2345](https://cloud.githubusercontent.com/assets/18699503/14851104/b5de2e44-0c4b-11e6-82b0-3cf897804d9a.JPG)

Notice the tops of the Title and lower case 'e' and 'a' in Chelsea Handler

**Comment by Narflex** [comment]
Erase the 'fontcache' directory in your SageTV program folder and that should fix the problem. There was a change to some of the font calculations recently to fix a bug so the cached ones are probably not lining up with the new calculations.
