### ISSUE TITLE
Task manager shows that "SageTVTranscoder.exe" has high cpu usage(37%) and the "Video Conversions" screen shows that nothing is being transcoded.

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#139]
[sagetv_0.zip](https://github.com/google/sagetv/files/277851/sagetv_0.zip)

**Comment by Narflex** [comment]
This is normal if you've added new files to the library (which you did according to the log). It's using FFMPEG (SageTVTranscoder.exe) to do format detection on file types the internal format parser doesn't handle.  This CPU usage is temporary and it runs it at a low priority and also monitors the process and kills it if it takes too long.
