### ISSUE TITLE
IsChannelViewable filter on GetAllChannels() includes an non-viewable channel

### ISSUE THREAD

**Issue by JREkiwi** [google/sagetv#144]
Ran into a problem when trying to debug an issue with the MiniGuide plugin
```
GetAllChannels()
    FilterByBoolMethod(this, "IsChannelViewable", true)
       Channels = Size(this)
```
returns the number of viewable channels + 1
```
GetAllChannels()
    FilterByBoolMethod(this, "IsChannelViewable", true)
       Channels = GetElement(this,0)
```
returns Channel[stationID=0, Name=]

The Program Guide also shows a blank channel
![image](https://cloud.githubusercontent.com/assets/14258403/16281301/dfe2fc30-3917-11e6-91a2-843adfb22886.png)

**Comment by Narflex** [comment]
Yeah, I recall causing this problem awhile back for a change I made for
Google Fiber (VOD items have no channel, but they can be viewable, so we
had to modify this to account for that case).  I *thought* I changed it
back for the open source release, but apparently not. This is an easy fix;
just edit java/sage/api/ChannelAPI.java where this API call returns true if
the station ID is zero (the code before Google did not have that condition
in it; I verified that).

On Wed, Jun 22, 2016 at 1:00 PM, JREkiwi <notifications@github.com> wrote:

> Ran into a problem when trying to debug an issue with the MiniGuide plugin
>
> GetAllChannels()
>     FilterByBoolMethod(this, "IsChannelViewable", true)
>        Channels = Size(this)
>
> returns the number of viewable channels + 1
>
> GetAllChannels()
>     FilterByBoolMethod(this, "IsChannelViewable", true)
>        Channels = GetElement(this,0)
>
> returns Channel[stationID=0, Name=]
>
> The Program Guide also shows a blank channel
> [image: image]
> <https://cloud.githubusercontent.com/assets/14258403/16281301/dfe2fc30-3917-11e6-91a2-843adfb22886.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/sagetv/issues/144>, or mute the thread
> <https://github.com/notifications/unsubscribe/ANEIDHbTRALwYhXnKU79wDgyEvkPqzaxks5qOZRcgaJpZM4I8KYy>
> .
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by JREkiwi** [comment]
Thanks Jeff,  now I just need someone who speak javanese to pick this up.

John

**Comment by Narflex** [comment]
I'll do it in a couple weeks when I'm back from vacation if nobody else
does.

Jeff Kardatzke

**Comment by CraziFuzzy** [comment]
Vacation!  You'll miss all this insanely hot weather in socal!

**Comment by enternoescape** [comment]
That was some very low hanging fruit if I looked at this right. #145

**Comment by Narflex** [comment]
Thanks!
