### ISSUE TITLE
Keep Sage Alive during Conversion

### ISSUE THREAD

**Issue by RBraverman** [google/sagetv#147]
A small tweak (hopefully) to alert Win7 and above that SageTV is really doing something.

**Comment by CraziFuzzy** [comment]
Already reported in Issue #148 (sorry, got impatient and beat you to it.  Changes have already been made and are just awaiting approval so hopefully the next build that goes out will include this change.

**Comment by 49studebaker** [comment]
Could you add an option in "Detailed Setup", that allows SageTV to sleep if a video is being converted? I would prefer that video would only be converted while video is being watched or SageTV is recording a show.

**Comment by RBraverman** [comment]
Rrealize this was a while back, but THANKS Fuzzy. Just got around to looking at Github - I know, I know, should do this more often.

**Comment by 49studebaker** [comment]
Version 9.0.12 (2016-12-22) change log

New: SageTV server will no longer allow the server to go to sleep until video conversions are complete.


I think this issue is resolved.
