### ISSUE TITLE
Make Network Encoder Discovery enabled by default.

### ISSUE THREAD

**Issue by CraziFuzzy** [google/sagetv#150]
I'm thinking about this, and I can't see a negative to changing this.  Since a LOT of the sources out there are using network encoders these days, and any future development makes sense to be in network encoder form, I think discovery should probably be turned on by default.  Anyone see a problem with this?

**Comment by Narflex** [comment]
At first I thought it'd be an issue...but then once I remembered that
SageTV's own encoding server is off by default; this should not show up as
any surprises to anyone (i.e. they'll start seeing encoders in setup they
didn't want to see).

On Sat, Jun 25, 2016 at 8:49 PM, Christopher Piper <notifications@github.com
> wrote:

> I'm thinking about this, and I can't see a negative to changing this.
> Since a LOT of the sources out there are using network encoders these days,
> and any future development makes sense to be in network encoder form, I
> think discovery should probably be turned on by default. Anyone see a
> problem with this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/sagetv/issues/150>, or mute the thread
> <https://github.com/notifications/unsubscribe/ANEIDGPG4wNvBMSnOJGM8RuxWpngwg_Eks5qPfbOgaJpZM4I-etm>
> .
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by Narflex** [comment]
This change was done by Fuzzy.

**Comment by jwittkoski** [comment]
For reference: This was changed in commit a79f78d74961615d8251cc77d8753a9e40dac5f0.
