### ISSUE TITLE
API call that allows a favorite to be disabled.

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#154]
There is a plugin that allows a user to disable a favorite, but the favorite's additional airing are hidden when the favorite is disabled. I would like to be able to view a favorite's additional airing when a favorite is disabled.

**Comment by 49studebaker** [comment]
I downloaded the latest SageTV download and it is now possible to disable a favorite without installing a plugin. I am still not able to view a disabled favorites "Aditional Airings".

**Comment by skiingwiz** [comment]
I have most of the work done for this. I just need to find some time to finish it. I am adding a new API method to retrieve a favorite's airings ignoring the disabled state. The STV will then use the new method to show additional airings.

**Comment by skiingwiz** [comment]
This is now available in 9.0.15. If you use the installer, you'll have to wait for a new version of that to be built. 

Someone with permissions may close this issue.
