### ISSUE TITLE
"Original Airing Date" is missing from some recordings.

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#181]
I moved my Outer Limits(1960s) recordings from my SageTV recording directory, to a folder on my external harddrive. I added the folder to my SageTV "Video Recording Directories". These recordings appear on my recordings screen but the "Original Airing Date" is missing. The "Aired On" date, "Season/Episode", "Category" and "Channel" are not missing. When I recorded these shows they had an "Original Airing Date". Is it possible to hide these recording when my external drive is disconnected?

**Comment by Narflex** [comment]
Is the original airing date always missing from moved recordings like
this...or just some of the time? And did you notice any pattern to when
it's missing?

Jeff Kardatzke

**Comment by Narflex** [comment]
Stale issue with no feedback, closing.
