### ISSUE TITLE
Non accessable recordings displayed on recordings screen

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#183]
I moved recordings to my external drive. I disconnected my external drive. I did a "Scan Imported Media" and a "Rescan Existing Library Files". SageTV still lists these recordings on the recordings screen. If a drive is disconnected, could you have SageTV hide these recordings since they can not be accessed?

**Comment by CraziFuzzy** [comment]
That is not how sage is designed.  The expectation is that the loss of the drive is temporary, so it does not remove those recordings from the database.

**Comment by 49studebaker** [comment]
I set these recordings as "archived".  Problem solved.
