### ISSUE TITLE
No specific User Agent for SageTV

### ISSUE THREAD

**Issue by CraziFuzzy** [google/sagetv#2]
When downloading content (or anything) using sage.FileDownloader, no user_agent is specifically set, so it uses the default "Java/x.x.x_xx" user_agent.  It seems to be more 'correct', it should be setting a user_agent that would be more like "SageTV/x.x.x".  This should be able to be done by either:
1.  Adding it directly into FileDownloader, which would require some logic to build the string from the current build version.  This is the quickest way to implement this.  The downside is it would not allow a way to 'force' the user agent to something else, which might be required when trying to access some sources.
2.  Using the already implemented requestProps argument in FileDownloader to pass the user agent from the calling library (usually Global.StartFileDownload).  This would then likely require adding an overloaded argument to the StartFileDownload function to allow the API call to set the User Agent, which if NOT set would default to "SageTV/x.x.x"

The immediate reason I am wanting this implemented is so that PlayOn can recognize SageTV, so SageTV can be white-listed as an HD capable player, which is the only way PlayOn will stream content in HD.  Option 2 would allow sage to emulate an already white-listed player to get PlayOn in HD immediately.  Option 1 would require PlayOn to have SageTV added to it's white-list before it would work in HD.

**Comment by Narflex** [comment]
One thing I'm not following....is can't this already be done using the StartFileDownload API call?  It sounds like #2 is already implemented. Take a look at the overloaded StartFileDownload API call in sage/api/Global.java. IIRC, that's why I added that argument in the first place. :)

And the main reason this was never set as the default was I didn't want SageTV getting blacklisted from specific sites.

**Comment by CraziFuzzy** [comment]
At a glance, it didn't look like StartFileDownload actually passed through anything but ServerAddress, SourceFile, and DestFile when it calls downloadFile.

**Comment by CraziFuzzy** [comment]
On another look, it looks like StartBackgroundFileDownload handles the props...

**Comment by CraziFuzzy** [comment]
but StartFileDownload and StartCircularFileDownload do not.

**Comment by Narflex** [comment]
Ahh yes, you are correct. :)

OK, I'd propose making 2 changes then.

1. Have a property such as "use_sagetv_user_agent" which then uses "SageTVa.b.c" as the user agent (and it would default to not being on for backwards compatibility)

2. Add an overloaded StartFileDownload API call which takes a RequestProperties parameter so this can force the user agent to whatever it wants.

That all sound good?

**Comment by CraziFuzzy** [comment]
Sounds prefect.  I had originally envisioned a single property that would simply override the user agent all the time, but later realized this would not really be proper, and any workaround user agent spoofing should be done on a case by case basis, so this solution should work best.  Default to old behavior, ideal having the property turned on which would have a "proper" default SageTV user agent, and provide a case by case way to workaround individual site issues with a spoofed user agent.

So, this would require downloadFile to generate a default, and apply it, if desired by global property, BEFORE the requestProps are iterated through.  Then the addition to the other Global API calls to pass through the props if there.

**Comment by CraziFuzzy** [comment]
Looks like I'll need some help if I'm going to complete this issue.  I'm not sure how, or if, the API functions CAN be overloaded.  Or at least if they can, I'm not sure about the way to go about doing so.  This leaves the only option to create a new API call (StartFileDownloadWithProps) with the properties attached.  I'm guessing there's no problem with doing this, it just means that any stv's or libraries that might benefit from the change will have to make sure to use the proper call.

**Comment by Narflex** [comment]
Take a look at the "SageCommand" API call in Global.java. That gives you an example of how it's done. The few things you need to notice are:

1. The # of parameters for the method is declared as -1 (in the constructor)
2. It uses the 'curNumberOfParameters' variable to determine how many arguments there are and then does the appropriate thing after that.
3. There's 2 javadoc comments, one for each method
