### ISSUE TITLE
STV depedency for plugins - allows only one

### ISSUE THREAD

**Issue by jusjoken** [google/sagetv#203]
If a plugin is compatible with more than 1 STV such as SageTV7 and Gemstone there is no way to specify an OR type dependency in the plugin manifest.  I assume we could have the author provide duplicate manifests with two id's and a different STV dependency but i wondering how we could allow for listing multiples.  Leaving the dependency out of the manifest could work as well but that could lead to other issues too.

**Comment by CraziFuzzy** [comment]
No, there's not currently any 'OR' features in the manifests.  The way UI Mods are built, and the ties to the widgets in the base STV, I honestly can't envision it every working very well to have the same stvi for more than one (actually different) STV.

**Comment by jusjoken** [comment]
Its not difficult to make happen and its what i have done for gemstone 2 even though i stripped most of the core stv elements from gemstone i have purposely left behind key hooks that some stvi's use and then i get a clean install.  Some stvi's like infopopup already are STV independent but for that one the stv dependency could be removed. It would be nice to understand how to make this happen.  i will review the code and see if i could understand it.

**Comment by jusjoken** [comment]
It looks to me that in "isSTVCompatible" in the PluginWrapper we could loop through all dependencies even after finding the first STV type and return true if any match...otherwise return false.  I have not found the code that loads the dependencies to see if it would actually read 2 STV type dependencies from the manifest.

**Comment by CraziFuzzy** [comment]
I think it's a plain SAX parser, so it will probably bring in any elements in the XML, including multiple STV dependencies (it just creates a collection of dependency objects, each with their own 'type' set.  Doesn't look like there's checking for conflicts like more than one dependency with the type "STV".

**Comment by jusjoken** [comment]
I checked it out....looks doable.  When I find a few minutes I may try a small change to the isSTVCompatible call and see if I can get it to handle multiple entries.  Thanks

**Comment by CraziFuzzy** [comment]
Actually, in looking at isSTVCompatible, it looks like it will already work with multiple STV dependencies.  It will loop through all dependencies, and it they are STV type, will check the name.  If name is not a match, it will continue on to the next dependency.  If name is a match, it will check if the version is good, and if so, return true.  So it will check all STV dependencies, until it finds one that is valid.  So you should be good to go with no core changes at all.

**Comment by jusjoken** [comment]
I just tested it and you are right.  It already handles this case.  So I will close this (and test before opening in the future!)
