### ISSUE TITLE
Autogenerated thumbnails don't obey image orientation

### ISSUE THREAD

**Issue by Narflex** [google/sagetv#205]
If you have a JPEG image that has an EXIF orientation set so it requires rotation, but that JPEG image does not have an embedded thumbnail in it (this is uncommon, but I have some pictures like this); then when SageTV generates the thumbnail it will not be at the proper orientation.

Technically this should be fixed for 2 cases...the Java image loader and the native image loader. But I don't think anybody uses the Java image loaders anymore because they are not enabled by default and really have no use anymore that I can think of.

The problem with the native image loader is that when it creates the thumbnails (using ImageLoader.createThumbnail) there is no rotation parameter passed in, so it generates the thumbnail off the unrotated image...but before it does that, it calculate the output dimensions from the rotated image. So the result has the wrong aspect ratio and the wrong rotation. I *think* this can simply be fixed by passing the rotation parameter into createThumbnail and then propogating that into the native LoadJPEG function.

**Comment by CraziFuzzy** [comment]
If the createThumbnail is going through the processing necessary to scale an image anyway, wouldn't it be better to simplify the resulting image as much as possible, so actually performing the rotation and not bothering the renderer with having to rotate it?

**Comment by Narflex** [comment]
The renderer doesn't do the rotations...the image loader does. Currently, it applies the same rotation to the embedded thumbnail as it does to the main image.

What I'm proposing here would rotate the image before the thumbnail is generated, so then the generated thumbnail (that's a standalone file) would require no rotation at all to be displayed (and it won't rotate external thumbnail files, only embedded ones).

**Comment by CraziFuzzy** [comment]
Oh.. okay... I thought you were talking about simply duplicating the rotation tag into the output file.

**Comment by Narflex** [comment]
And apparently it's not this simple...if you do what I said then you end up with a corrupted image that clearly looks like it has bad width/height/scanline something wrong (zig-zag patterns in the image with misaligned pixels).  The dimension handling in the rotation code is somewhat awkward and I need to redo it to handle this case. At first I thought it just wasn't handling rotation of 24 bpp images (and it appeared as if it never hit a block of code in that case for rotation at first)...but I think it might be worse than that. I definitely don't want to break anything existing that works, so I need to be careful here. :)

**Comment by Narflex** [comment]
OK, figured it out by cheating...apparently if I just use 32 bpp images, then I don't need to change anything at all in the native loader code and it works fine. :)
