### ISSUE TITLE
Directx9 Render failed

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#206]
Directx9 Render failed error message

**Comment by 49studebaker** [comment]
[SageTV errors.zip](https://github.com/google/sagetv/files/565359/SageTV.errors.zip)

**Comment by jusjoken** [comment]
not sure its related but i am seeing this on one of my windows server 2012r2 test vm's.  I have not had time to chase it down yet but the logs fill fast with the error and then java dumps.

**Comment by jusjoken** [comment]
I have been able to recreate this issue and narrow it down.  I believe this is related to using Java 8 with SageTV 9 in windows.  I have a VM where I rolled back to prior to upgrading to java 8 and this failure does not occur.  Once Java 8 is upgraded, then this error occurs again.

I am not sure how to narrow the issue down to determine what is causing it so would approeciate any guidance on trapping the real issue.

I included a crash log that I think is related and it does mention some failures in jni.cpp but I am not sure how to interpret any of this.

[hs_err_pid5660.txt](https://github.com/google/sagetv/files/569234/hs_err_pid5660.txt)

**Comment by 49studebaker** [comment]
Sagetv appears to be missing scheduled recording,  could this error be the cause of the problem?

**Comment by Narflex** [comment]
49Studebaker is having this problem: D3DERR_NOTAVAILABLE when calling CreateDevice, so this is just an overall failure loading the 3D system. At one point it just starts working again...maybe its some kind of power management issue with the graphics card...or a driver issue...but I don't think there's anything that can be changed in SageTV to help it.

**Comment by Narflex** [comment]
@jusjoken Can you get me a log file (not just the hs_err_pid file) from this with Java 8?  I'm also suspicious of this running inside a VM...that could definitely impact the way it accesses the 3D system (but the Java dependency is very interesting...maybe they changed something when running in a VM with how it gives access to native window handles).

**Comment by jusjoken** [comment]
Zip of sage log attached.  I will try to setup a windows laptop and repeat the test to see if the same occurs.  The VM works fine with Java 7 and the same release of Sage so something specific to Java 8 is causing this.

[sagetv_0_fail.zip](https://github.com/google/sagetv/files/569903/sagetv_0_fail.zip)

**Comment by Narflex** [comment]
You're having the same error where all of a sudden the Direct3D device reports that it is 'lost' (which can happen during things like standby or resolution changes), and SageTV tries to rebuild it when that occurs. But it keeps failing when it tries to rebuild it....then it succeeds again finally...fails...then succeeds again.

It's interesting that this is linked to a version of Java. First thing to try is setting this environment variable for when you run SageTV:

J2D_D3D=false

That should turn of Java's use of Direct3D itself. This shouldn't affect SageTV's usage of it though because it uses its own native code and doesn't need any 3D acceleration help from Java at all. If this does fix the problem, then we can just force this in the EXE when it creates the JVM so then it won't hit other people.

**Comment by jusjoken** [comment]
Ok...I have now also recreated the issue with Java 7 so it is not Java related.  Your explanation above makes sense as I remote desktop to my VM's and I assume when I minimize the RDP session then the Direct3D device is likely reporting lost.

Odd I have never noticed this in the past as I do all/most of my development and testing using an RDP session and have never seen the logs fill up like this.

I am still in the middle of getting a laptop setup to test but that is likely no longer needed given your explanation above.

I will also try the environment variable "J2D_D3D=false" and see if that changes anything.

Thanks

**Comment by jusjoken** [comment]
I did more testing.  On the laptop this never occurred.  On the RDP session to either of the test VM's I use it happens always when I minimize the RDP session and then return after a few minutes.  If I leave it for hours then I get MANY log files filled with these log entries.  Perhaps it always did this and I never noticed.  

Anyway....not an issue for me as I only use the VM's for testing and development and the log entries do not seem to cause an issue other than the 1 crash which may be unrelated.

As info, the "J2D_D3D=false" environment variable did not change this.

Thanks

**Comment by Narflex** [comment]
Ok, thanks for the info, nothing else to do about this one. :-)

**Comment by 49studebaker** [comment]
I did a clean install of Windows 10 and this problem  no longer occurs.
