### ISSUE TITLE
SageTV7 STV - remove some checks for versions

### ISSUE THREAD

**Issue by jusjoken** [google/sagetv#207]
Given that our update mechanism is now GitHub and version releases through BinTray I believe we should remove the code from the core STV that checks for new STV versions as well as new firmware and releases.  Likely we should review the 3 threads that do checking....
- Starting Online Video properties updater thread
- Starting STV update availability check thread
- Starting SageTV & Firmware version upgrade availability check thread

I may look at this myself but thought I'd get consensus or concerns.

**Comment by Narflex** [comment]
I have no problem with this. :-)

Jeff Kardatzke

**Comment by jusjoken** [comment]
I posted a new STV that removes this unused functionality.

**Comment by jusjoken** [comment]
Fixed with PR [209](https://github.com/google/sagetv/pull/209)
