### ISSUE TITLE
SageTV server software on android TV box

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#216]
Is it possible to run the SageTV server software on a device like this:

http://m.gearbest.com/tv-box-mini-pc/pp_414192.html

**Comment by CraziFuzzy** [comment]
Not really the best place to discuss this (the forum would be better). However, that box is Android, and no sagetv server software is available for android. That box may work well with the miniclient, but that's about it as far as saegtv is concerned.

**Comment by 49studebaker** [comment]
Could you make it possible for SageTV server to run on an android TV box?

**Comment by Narflex** [comment]
Yes it should be possible, but it would likely be a significant amount of
work.

Jeff Kardatzke

**Comment by Narflex** [comment]
I don't think this will ever be implemented, there's no reason to do it since there's not going to be much storage on an Android box.
