### ISSUE TITLE
Force debug logging on all the time

### ISSUE THREAD

**Issue by Narflex** [google/sagetv#238]
Does anybody see any issue with this?  It's not really any kind of performance problem and it would eliminate that annoying troubleshooting step of making sure it's on.  We had it on for Google Fiber on all of our boxes so we could analyze issues...and those were very low powered.

I wouldn't even give an option to turn it off...just make it always on, all the time....and then also remove the UI option for turning it on/off.

**Comment by enternoescape** [comment]
I think this is a good idea. If we do this, we should probably also remove the option from the UI too.

**Comment by technazz** [comment]
Yes for sure :).
