### ISSUE TITLE
9.1.2 won't start due to script error in startsagecore

### ISSUE THREAD

**Issue by Greg2dot0** [google/sagetv#297]
System: Ubuntu 16.04 Server (64-bit)

I get the following error when installing 9.1.2

`May 31 06:27:20 sagetv-g2 systemd[1]: Starting LSB: SageTV Server...
May 31 06:27:20 sagetv-g2 sagetv[2037]: Starting SageTV Server: sagetvChanging to SageTV directory /opt/sagetv/server
May 31 06:27:20 sagetv-g2 sagetv[2037]: .
May 31 06:27:20 sagetv-g2 systemd[1]: Started LSB: SageTV Server.
May 31 06:27:20 sagetv-g2 sagetv[2037]: Executing pre-scripts
May 31 06:27:20 sagetv-g2 sagetv[2037]: ./startsagecore: line 36: syntax error in conditional expression: unexpected token `;'
May 31 06:27:20 sagetv-g2 sagetv[2037]: ./startsagecore: line 36: syntax error near `;'
May 31 06:27:20 sagetv-g2 sagetv[2037]: ./startsagecore: line 36: `if [[ "$JAVA_VERSION" == "8" || "$JAVA_VERSION" == "9"]] ; then'
`
Trying to work through the script, but not seeing why it's throwing an error in 9.1.2 and not in 9.1.1
Here's the 9.1.2 code

`JAVA_VERSION=$(java -version 2>&1 | grep -i version | sed 's/.*version ".*\.\(.*\)\..*"/\1/; 1q')
if [[ "$JAVA_VERSION" == "8" || "$JAVA_VERSION" == "9"]] ; then
    JAVAOPTS="$JAVAOPTS -XX:+UseG1GC -XX:+UseStringDeduplication"
fi`

Here's the 9.1.1 code
`java_version=$(java -version 2>&1 | awk -F '"' '/version/ {print substr ($2, 0, 4)}')
if [[ "$java_version" == "1.8" || "$java_version" == "1.9" || "$java_version" == "1.8." || "$java_version" == "1.9." ]] ; then
    JAVAOPTS="$JAVAOPTS -XX:+UseG1GC -XX:+UseStringDeduplication"
fi`

**Comment by Greg2dot0** [comment]
Seems that by removing the second set of brackets resolves the issue.

if [ "$JAVA_VERSION" == "8" || "$JAVA_VERSION" == "9"] ; then

**Comment by enternoescape** [comment]
This has been addressed in pull request #295 .

**Comment by enternoescape** [comment]
I spotted the problem when I upgraded last night. When I submitted the change, I failed to notice a space was missing (I really did test this change before committing) and the startup scripts don't get tested by Travis CI. That might be something we should change to prevent silly mistakes like this in the future.
