### ISSUE TITLE
Add support for all 4 tuners of Hauppauge WinTV-quadHD board

### ISSUE THREAD

**Issue by JustFred51** [google/sagetv#318]
Hauppauge has discontinued new sales of the older 2250 and 2255 dual tuner PCIe cards.  They've been replaced by the "WinTV-quadHD" 4-tuner card.
Currently, Sage only allows access to 2 of the 4 tuners under Windows.

The 2 tuners show up as:
Hauppauge WinTV 885 TS Capture 
Hauppauge WinTV 885 TS Capture #2

With this change, Sage sees all 4 tuners:
Hauppauge WinTV 885 TS Capture 
Hauppauge WinTV 885 TS Capture #2
Hauppauge WinTV 885 TS Capture 2
Hauppauge WinTV 885 TS Capture 2 #2

**Comment by Narflex** [comment]
When you say "with this change" Sage sees 4 tuners...what change are you referring to? Do you know how to fix the problem? :)

**Comment by JustFred51** [comment]
I've already implemented the fix in my local repo and tested it.  With the fix, I can now see all 4 TS Capture devices.  
I''ll be creating a pull request shortly.  
Right now I'm trying to re-learn how to use Git (I'm a ClearCase guy)... can't figure out how to assign this issue to myself and tag it as "Enhancement".

**Comment by stuckless** [comment]
When you look at your issue (assumed your are logged into GitHub).  On the right there is **Assignees**, **Label**, **Projects**, etc.  Under the, **Assignees** thes is text/link **assign yourself**, just click that ;)

For tagging it an enhancement, just click the Labels bold header, and then select enhancement.

**Comment by JustFred51** [comment]
Yes, I'm signed in and do see Assignees, Label, etc, but they're not clickable.  I must be missing something obvious.  The only clickable item on the right is "Unsubscribe".

**Comment by enternoescape** [comment]
I am unable to tag or assign anything either. I believe this is a permissions related issue.

**Comment by JustFred51** [comment]
Thanks for the sanity check.  Someone who **does** have permissions can feel free to assign this one to me and mark it as an Enhancement.

**Comment by Narflex** [comment]
Done ☺️

**Comment by JustFred51** [comment]
The code changes needed to resolve this issue were handled by pull request in Issue #320 

Magic text to close #320 when closing this issue:
Fixes #320
