### ISSUE TITLE
Linux - Video Thumbnails Not Displayed

### ISSUE THREAD

**Issue by KeithAbbott** [google/sagetv#332]
Linux version behaves differently than the Windows version for video thumbnails.  Windows version treats thumbnail.jpg identical to thumbnail.JPG.  Linux version displays thumbnail.jpg properly, but ignores thumbnail.JPG

Please modify Linux SageTV to handle video thumbnails jpgs properly, regardless of the case of the extension.

**Comment by stuckless** [comment]
We don't have the ability to modify how the filesystem API works from within SageTV.  In windows, the filesystem is case insensitve.  So THUBMNAIL.JPG and ThUmBnAiL.JpG are the same file.  In Linux those are two separate files (as the filesystem is case sensitive).   Code could be written in sagetv to solve this, but, it would require reading all files in a driectory and then scanning the names in a case insensitive way and that would be brutally slow.

If SageTV, linux, is creating thumbnail.JPG and thumbnail.jpg then that would be a bug.  But if you just happen to drop in thumbnail.JPG and want SageTV linux to use that, then that's likely never getting "fixed".

Windows is the only fileystem I know of that actually treats these two files as being the same.

My suggestion would be to use a file renamer tool to find all thumbnail.JPG files and then rename them to thumbnail.jpg.

**Comment by KeithAbbott** [comment]
OK, thanks for the explanation!
