### ISSUE TITLE
HD PVR 60 With 9.1.8 Network Encoding

### ISSUE THREAD

**Issue by 66cobra** [google/sagetv#369]
I upgraded Win10 network encoder to 9.1.8 and installed HD PVR 60 and associated drivers. Network encoder itself has no issues playing back content, but the Linux host instance of SageTV (9.1.7.581) is not receiving the stream from the network encoder. Network encoder status on the host is true/true, but it doesn't appear that the network encoder is even attempting to tune the channel locally. Changing back to HD PVR produces the stream on the host. 
Please let me know which combination of the logs is best to collect and attach, as I do see same behavior during both, adding the source and actual tuning from the program guide.

Thanks.

**Comment by JustFred51** [comment]
I'm pretty sure that the software version of the Sage Client must match the Server version.  Please report back after updating the Linux client.

**Comment by 66cobra** [comment]
I don't believe client/server versions statement is applicable in this case, as this is a case of 2 servers, one as host, one as network encoder.

**Comment by wnjj** [comment]
Start with the sagetv_*.txt log files from both machines.  Usually sagetv_0.txt is enough if you save them shortly after causing the issue.

**Comment by 66cobra** [comment]
Compiled 9.1.8 on Linux, working perfectly with Win10 nwk encoder.
