### ISSUE TITLE
Current toolset requirements for building native code?

### ISSUE THREAD

**Issue by JustFred51** [google/sagetv#38]
What is the current minimum toolset requirement for building native code?  From the "VS2005 build environment" forum thread, my understanding is: JDK (README at the top of the tree says minimum 1.5 ), DirectX SDK, Windows SDK v6.1 and Visual Studio 2005.  Can someone confirm or correct this?  I ask because there are recent commits that seem to refer to system #includes that aren't satisfied by the environment described above.  Example: "include <inttypes.h>".   It might be helpful for us to be in sync on the toolsets & versions.  I understand that the goal is to move to a newer version of VS (presumably VS2015 Community) in the near future.  But what are people building native code with **now**?

**Comment by JustFred51** [comment]
Was hoping that the community would chime in.  With no response, I'm going to propose the following:
1. DirectX SDK (June 2010), MS's "final" release of DXSDK
2. Windows SDK v6.1, (last release that included qedit.h)
3. Visual Studio 2015 (Community Edition)

Based on the above, I'm very close to a commit that will update the build environment for windows native code.

**Comment by Narflex** [comment]
This all sounds fine to me as long as VS 2015 (Community Edition) is
something that can be downloaded freely. IIRC there is a way to do that;
although it's not on Microsoft's site.

On Sun, Oct 11, 2015 at 11:56 AM, Keith Fischer <notifications@github.com>
wrote:

> Was hoping that the community would chime in. With no response, I'm going
> to propose the following:
> 1. DirectX SDK (June 2010), MS's "final" release of DXSDK
> 2. Windows SDK v6.1, (last release that included qedit.h)
> 3. Visual Studio 2015 (Community Edition)
>
> Based on the above, I'm very close to a commit that will update the build
> environment for windows native code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/38#issuecomment-147235178>.
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by JustFred51** [comment]
VS2015 Community Edition is a free download.  It includes MS's refactored libraries, full toolset and integration with Git.  I've successfully migrated the Solution, got everything to build in VS2015 and am running the resultant binaries (exe, dll and ax).  I've also brought the Directshow BaseClasses into third_party\Microsoft so that it automatically builds within the Solution.  Doing so avoids the old way of having to manually copy from SDK 6.1 & manually build them "someplace else",  It insures that the toolset settings are consistent across the entire Solution.  As part of the commit, there is a HOWTO that details exactly which environment variables, SDKs, etc. are needed and where to download and set them up.   I plan to generate a pull request as soon as I understand exactly how to use Git's branching model.

**Comment by Narflex** [comment]
Awesome work so far. :)

On Mon, Oct 12, 2015 at 6:38 PM, Keith Fischer <notifications@github.com>
wrote:

> VS2015 Community Edition is a free download. It includes MS's refactored
> libraries, full toolset and integration with Git. I've successfully
> migrated the Solution, got everything to build in VS2015 and am running the
> resultant binaries (exe, dll and ax). I've also brought the Directshow
> BaseClasses into third_party\Microsoft so that it automatically builds
> within the Solution. Doing so avoids the old way of having to manually copy
> from SDK 6.1 & manually build them "someplace else", It insures that the
> toolset settings are consistent across the entire Solution. As part of the
> commit, there is a HOWTO that details exactly which environment variables,
> SDKs, etc. are needed and where to download and set them up. I plan to
> generate a pull request as soon as I understand exactly how to use Git's
> branching model.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/38#issuecomment-147569990>.
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by JustFred51** [comment]
Posted the info about completed migration to VS2015 to http://forums.sagetv.com/forums/showthread.php?t=62588
