### ISSUE TITLE
Default recordings as MPEG-TS?

### ISSUE THREAD

**Issue by jwittkoski** [google/sagetv#439]
Now sure if this is a bug or "as intended":

Sage.properties has a setting `encode_digital_tv_as_program_stream`

I thought setting this to `false` would generate MPEG-TS files instead of MPEG-PS files.

However, when testing, I shut down Sage, changed all the occurrences of encode_digital_tv_as_program_stream from true to false, restarted, and recorded something from my HDHR Quatro, which Sage records from directly (not using OpenDCT or another network encoder).

The result was a file with a .ts file extension, but ffprobe reports the file is actually MPEG-PS ("input" shown as "mpeg", whereas MPEG-TS containers would show the "input" as "mpegts"):

```
Input #0, mpeg, from 'ShippingWars-NotWithaWhimperbutaBang-60182708-0.ts':
  Duration: 00:07:07.32, start: 1.069356, bitrate: 2214 kb/s
    Stream #0:0[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv), 704x480 [SAR 40:33 DAR 16:9], Closed Captions, max. 4874 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
```
mediainfo also confirms it's actually MPEG-PS:
```
Complete name                : ShippingWars-NotWithaWhimperbutaBang-60182708-0.ts
Format                       : MPEG-PS
File size                    : 227 MiB
```
So when this setting is `false` it doesn't seem to actually create recordings as MPEG-TS containers.

**Comment by Narflex** [comment]
This setting used to work a long time ago, but then things got changed at one point and I know we never fixed it so it works properly. So this doesn't surprise me.
