### ISSUE TITLE
Hotspot on initial setup

### ISSUE THREAD

**Issue by yoavp77** [google/sagetv#53]
Finally found some time to try out the OSS version of sagetv, but I'm not having much luck with it. It's hotspotting consistently on a vanilla installation of the latest commit on gh. I'm running it on ubuntu 14.04 and using the tarball version after following the instructions on the sticky post on the forum. It's not %100 clear which version of Java to use - I tried Sun java 8, 7, and 6.

I get the error as soon as I try to set up external tuning for my hdpvr, so before installing any plugins or setting anything up. The hdpvr also isn't even lighting up blue when I select 'component' input in the sources menu (but it does when I cat /dev/video0 > /Dev/null)

You can see the errors at:
http://pastebin.com/MUVw9rFh

**Comment by Narflex** [comment]
I'm fairly sure this one is fixed now, there was a 64 bit issue with pointer casts in the SFIRTuner library that was fixed awhile back.
