### ISSUE TITLE
Regular expression Keywords fail

### ISSUE THREAD

**Issue by nyplayer** [google/sagetv#57]
This works on SageTV7 but does not work on SageTV9. I am finding out the Sage9 is more limited in the way you can define favorites than Sage7. They all worked fine in Sagetv7. I was wondering why some shows were not recording. It appears that SageTV9 does not handle regular expressions as good as SageTV7.

examples do not work.
keyword christmas "MV\d+"

 Title Criminal Minds
 keyword "EP\d+"
 also
 Category Docudrama
 keyword "MV\d+"

**Comment by Narflex** [comment]
I'll make a fix for this. It'll just require a setting to have it work the
legacy way which is slower and bypasses Lucene for search.

Jeff Kardatzke

**Comment by CraziFuzzy** [comment]
Does lucene not support regex searches?

**Comment by stuckless** [comment]
Lucene does not support regex searches, but it does support many other complex searches and wildcard searches.

https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

Regex is basically a poor man's search engine... it works, but, not the most efficient way to search large collections.

**Comment by CraziFuzzy** [comment]
is this of any help?

https://lucene.apache.org/core/3_0_3/api/contrib-regex/org/apache/lucene/search/regex/RegexQuery.html

I understand regex is far less efficient, but efficiency is hardly important for this part of the code, and maximum customizibility of the filters/queries would be more important.

**Comment by Narflex** [comment]
I've submitted a change that fixes this and it is set that way by default. :)
