### ISSUE TITLE
Using depreciated Linux command to mount SMB shares

### ISSUE THREAD

**Issue by BobPhoenix** [google/sagetv#79]
Problem with SMBMOUNT command.  It has been depreciated in Linux and is no longer available in cifs-utils.  The code needs to be updated to include the newer method to mount SMB shares.  See this thread on the SageTV forums: http://forums.sagetv.com/forums/showthread.php?t=63002

**Comment by BobPhoenix** [comment]
See SMBMOUNT in IOUtils.java don't know if that is where the problem I've got is coming from or not.

**Comment by Narflex** [comment]
I think this got fixed because somebody changed it to check if 'smbmount' is available and if not then it uses 'mount.cifs' instead, so I'm going to close this now.

**Comment by BobPhoenix** [comment]
Yes I fixed it and you merged it a while ago.  Was I supposed to close it?
 Didn't know the person reporting the problem could do that.  Sorry about
that.

BobPhoenix

**Comment by Narflex** [comment]
I don't really know how this is *supposed* to work. :)  I know when you do checkins, you can reference an issue # in it to link the checkin to the issue..but I've only done that sometimes when I actually remember to.  I don't think that actually closes the issue though.

I was just looking through them all again and closing ones that I thought were done. So no worries. :)

I think I may be able to still link it..let me try that. #80

**Comment by Narflex** [comment]
Cool...looks like you can do it after the fact to some degree, although it's not part of the commit message then.

**Comment by stuckless** [comment]
Typically I will say something like, "Fixed #NNN" in the commit message and it will close the issue for me.    It's handy.
