### ISSUE TITLE
Video DVD/BD Sort Error

### ISSUE THREAD

**Issue by ddoell** [google/sagetv#89]
At the suggestion of jusjoken I am opening an issue regarding a v9 DVD/BD sort error. When using the windows installer release candidate to install v9 over v7.1.9 an anomaly occurred in Videos. Normally my DVD and BD rips are kept sorted alphabetically. After installing v9 the rips are scrambled generally into two groups with each group sorted mostly alphabetically. There are also 3 or 4 files that are not included in the two larger groups. This scrambling of titles makes access to the DVD and BD rips difficult and  reduces WAF. I tried to fix the sort with BMT with no luck. I tried using the v9 repair command with no luck. I tried deleting my Sage installation and installing v7.1.9 from scratch followed by installation of v9 using the windows installer with no luck. Finally I installed v7.1.9 followed by manual installation of v9 using the exe files and jars. Again no luck. In all cases the list of DVDs and BDs in v7.1.9 is listed correctly and in all installations of v9 the sort is scrambled. Also in all cases my OS was Windows 10 Pro. I have a little over 100 DVD and BD rips.

**Comment by Narflex** [comment]
Can you please provide specific examples of this? Screenshots are probably
good. I definitely need more data to go off here as I can't think of any
reason this would have changed.

I mainly need to know the grouping and sorting settings used on that menu,
and then a list of what order the titles are appearing in for each case.

Jeff Kardatzke

**Comment by ddoell** [comment]
Jeff,

 

I’ve attached screenshots of the options settings and all the screens in the DVD/BD sub-menu. Is this what you needed?

 

Dave Doell

**Comment by Narflex** [comment]
I'm not seeing any attachments...if you email attached them, you probably need to use the web interface to GitHub instead for them to show up.

**Comment by ddoell** [comment]
Sorry.....total noob to this Github thing. Trying again......
![capture0](https://cloud.githubusercontent.com/assets/17954880/13902352/be5919e6-ee12-11e5-8323-8ffac455ec7d.JPG)
![capture1](https://cloud.githubusercontent.com/assets/17954880/13902354/be5d5196-ee12-11e5-9875-f81b9086b811.JPG)
![capture2](https://cloud.githubusercontent.com/assets/17954880/13902353/be5b66c4-ee12-11e5-9c14-eccbefc0219f.JPG)
![capture3](https://cloud.githubusercontent.com/assets/17954880/13902355/be5d82b0-ee12-11e5-8baa-cf62bf332b07.JPG)
![capture4](https://cloud.githubusercontent.com/assets/17954880/13902356/be827732-ee12-11e5-88b7-acce60b572b7.JPG)
![capture5](https://cloud.githubusercontent.com/assets/17954880/13902357/be832b00-ee12-11e5-87bb-5b946b4d0965.JPG)
![capture6](https://cloud.githubusercontent.com/assets/17954880/13902358/be83b26e-ee12-11e5-94bc-57e748d6884f.JPG)
![capture7](https://cloud.githubusercontent.com/assets/17954880/13902359/be8bc09e-ee12-11e5-91f5-36b23915606c.JPG)
![capture8](https://cloud.githubusercontent.com/assets/17954880/13902360/be8cac5c-ee12-11e5-9df4-2231085a4b73.JPG)
![capture9](https://cloud.githubusercontent.com/assets/17954880/13902361/be92b67e-ee12-11e5-8603-a41857f842c5.JPG)
![capture10](https://cloud.githubusercontent.com/assets/17954880/13902362/be95aa96-ee12-11e5-9f4e-1c7798be7b97.JPG)
![capture11](https://cloud.githubusercontent.com/assets/17954880/13902363/be9725ec-ee12-11e5-8f89-25fa14bae61d.JPG)
![capture12](https://cloud.githubusercontent.com/assets/17954880/13902364/be9ac1ca-ee12-11e5-8f0f-4546d60e7965.JPG)
![capture13](https://cloud.githubusercontent.com/assets/17954880/13902365/be9bdf60-ee12-11e5-8467-3c24342504af.JPG)
![capture14](https://cloud.githubusercontent.com/assets/17954880/13902366/bea3f218-ee12-11e5-80bf-f43102f06c9d.JPG)
![capture15](https://cloud.githubusercontent.com/assets/17954880/13902367/bea45a78-ee12-11e5-82c3-25856984e444.JPG)
![capture16](https://cloud.githubusercontent.com/assets/17954880/13902368/bea68528-ee12-11e5-8469-c2f044e26d34.JPG)
![capture17](https://cloud.githubusercontent.com/assets/17954880/13902369/beb2ab82-ee12-11e5-8c25-3cae474866ca.JPG)

**Comment by Narflex** [comment]
That's very interesting. :-) Can you turn on debug logging in Detailed
Setup->Advanced and then go back into that menu and post the Sagetv_0.txt
log file please?

I'm wondering if that one which is not showing a title is causing an
exception during the sorting process and so it doesn't finish the sorting
and ends up like this. (This looks like a list that's a couple steps away
from finishing with a mergesort operation)

Jeff Kardatzke

**Comment by ddoell** [comment]
[sagetv_0.txt](https://github.com/google/sagetv/files/182650/sagetv_0.txt)

Here is the log file. That video with no name is a bluray disk of Lincoln. It is the one and only BD rip I ever did using the MKV file format. That file always gave me trouble in 7.1.9. I could never change the name of the title and it always listed it first in the sort.

**Comment by Narflex** [comment]
Sorry, I need the sagetvclient_0.txt file instead...I didn't realize you
were running in service mode.

On Mon, Mar 21, 2016 at 9:09 AM, ddoell <notifications@github.com> wrote:

> sagetv_0.txt <https://github.com/google/sagetv/files/182650/sagetv_0.txt>
>
> Here is the log file. That video with no name is a bluray disk of Lincoln.
> It is the one and only BD rip I ever did using the MKV file format. That
> file always gave me trouble in 7.1.9. I could never change the name of the
> title and it always listed it first in the sort.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/89#issuecomment-199359872>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by ddoell** [comment]
[sagetvclient_0.txt](https://github.com/google/sagetv/files/182814/sagetvclient_0.txt)

Here it is. Appears to be a lot of violence in this log :-).

**Comment by Narflex** [comment]
OK, here's the culprit:

Mon 3/21 11:27:34.411 [ReProcessHook@157958d] EXCEPTION in
getValueAsObject:sage.jep.ParseException: Error in method reflection of
SortLexical of java.lang.NullPointerException
for:SortLexical(SortedAllVideoFiles, !SortVideoListAscending,
"GetShowEpisode" )

Mon 3/21 11:27:34.419 [ReProcessHook@157958d] EXCEPTION in
getValueAsObject:sage.jep.ParseException: Error in method reflection of
SortLexical of java.lang.NullPointerException
for:SortLexical(SortedAllVideoFiles, !SortVideoListAscending,
"GetShowTitle" )

So the origin of it is what I expected it to be....but I can't tell why
it's actually having this problem. It *should* be printing out a stack
trace along with the error, but it's not for some reason. If you enable the
console window, then the stack traces will likely show up in there. Here's
how to do that:

http://forums.sagetv.com/forums/showthread.php?p=385086&postcount=209

Then get me the data from the console window after it hits the same errors
above (and then it should print out a dozen or more lines of where that
error actually originates from). Then I can pinpoint it.

On Mon, Mar 21, 2016 at 10:47 AM, ddoell <notifications@github.com> wrote:

> sagetvclient_0.txt
> <https://github.com/google/sagetv/files/182814/sagetvclient_0.txt>
>
> Here it is. Appears to be a lot of violence in this log :-).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/89#issuecomment-199399132>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by ddoell** [comment]
I'm not sure what I'm doing wrong. In post #209 from the thread you sent I see this comment: "The SageTV one with registry:
[HKEY_LOCAL_MACHINE\SOFTWARE\Frey Technologies\Common]
"consolewin"=dword:00000001"

I assume I need to make the above entry in the registry. But when I look in the registry editor under HKEY_LOCAL_MACHINE\SOFTWARE I don't see any entry for Frey Technologies. Does this have something to do with my having Windows 10?

**Comment by Narflex** [comment]
Yeah....Windows 10 is likely putting it somewhere else in there. I can't
remember off the top of my head where....but you can probably just do a
Find in regedit for "Frey Technologies" and you should find the section
that way.

Jeff Kardatzke

**Comment by ddoell** [comment]
Okay....I found one entry for Frey Technogies and it has a subdirectory called common. But there is no key called "consolewin." Is it supposed to be there already? If not do I need to add this whole key in Registry Editor with "common" highlighted in the left window and the new key added in the right window?

If I need to add it is it actually a key or is it one of the other choices under "new."

**Comment by ddoell** [comment]
I also see in the right pane with common selectect in the laft pane there is a key called default and it says value not set. Is this where I put consolewin?

**Comment by Narflex** [comment]
You need to create a new one on the right side.

Jeff Kardatzke

**Comment by Narflex** [comment]
And it's a new DWORD value you create.

Jeff Kardatzke

**Comment by ddoell** [comment]
nevermind......I found a better explanation on how to do this on the forum. give me a minute.

**Comment by ddoell** [comment]
Sorry about that. Your message came in while I was sending mine. I got it now. Data coming shortly......

**Comment by ddoell** [comment]
So I have an extra DOS screen now when I run SageTV. So do you want me to go to Videos by DVD\BD and then copy and paste all the info in the DOS screen? I found a message you sent to someone else back in 2004 that says to hit control break first. Do I need to do that?

**Comment by Narflex** [comment]
Yes, copy and paste from there. You do not need to do the Ctrl Break thing.

Jeff Kardatzke

**Comment by ddoell** [comment]
I hope this is what you are looking for:

image from file .\userdata\Phoenix\cache\imagetrans\PCwq\97d04ff6015e60ad29ff5422c832a223.jpg
Mon 3/21 13:50:12.016 [ReProcessHook@832b87]  ++++++++ Video folder browser:  LastCurFolder = null; CurFolder = null; LastVideoFolder = null
Mon 3/21 13:50:12.021 [ReProcessHook@832b87]  BEGIN: Refresh video folder info for CurFolder=[null]
Mon 3/21 13:50:12.027 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=295 h=457
Mon 3/21 13:50:12.030 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 295x442 for .\userdata\Phoenix\cache\imagetrans\PCwq\992bee29f4f9cdcc22659d7cc72480c1.jpg fileSize=24783
Mon 3/21 13:50:12.036 [ReProcessHook@832b87]  ==> Sort all video files: Time = '3'
Mon 3/21 13:50:12.041 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file .\userdata\Phoenix\cache\imagetrans\PCwq\992bee29f4f9cdcc22659d7cc72480c1.jpg
Mon 3/21 13:50:12.042 [ReProcessHook@832b87]  ==> Get video group via GetMediaFilesWithImportPrefix: Time = '0'
Mon 3/21 13:50:12.048 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=295 h=442
Mon 3/21 13:50:12.048 [ReProcessHook@832b87]   Done. SubFolderKeyList Size: 20, FolderMediaList Size: 108, CombinedFolderList Size: 128
Mon 3/21 13:50:12.055 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 295x442 for .\userdata\Phoenix\cache\imagetrans\PCwq\77872f72259d83cd9e60c78dcef09b23.jpg fileSize=39358
Mon 3/21 13:50:12.060 [ReProcessHook@832b87]  END: Video folder browser:  Reloaded folder info.  Total Time = '28'
Mon 3/21 13:50:12.065 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file .\userdata\Phoenix\cache\imagetrans\PCwq\77872f72259d83cd9e60c78dcef09b23.jpg
Mon 3/21 13:50:12.066 [ReProcessHook@832b87]  ++++++++ Video folder browser:  Reloaded folder info
Mon 3/21 13:50:12.071 [ReProcessHook@832b87] BEGIN: Sort non-DVD videos by title.
Mon 3/21 13:50:12.076 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=295 h=442
Mon 3/21 13:50:12.077 [ReProcessHook@832b87]  ==> Get non-DVDs via GetMediaFiles(): Time = '1'
Mon 3/21 13:50:12.083 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 166x161 for C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\dvd.png fileSize=33646
Mon 3/21 13:50:12.089 [ReProcessHook@832b87]  ==> Get non-DVD video files. Filter by not IsTVFile Time = '0'
Mon 3/21 13:50:12.093 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\dvd.png
Mon 3/21 13:50:12.095 [ReProcessHook@832b87]  ==> Sort non-DVDs via GetShowEpisode + GetShowTitle: Time = '2'
Mon 3/21 13:50:12.100 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=166 h=161
Mon 3/21 13:50:12.101 [ReProcessHook@832b87] END: Sort non-DVD videos. Found 148 videos. Total Time = '24'
Mon 3/21 13:50:12.106 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 254x254 for C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ThumbShadow.png fileSize=1772
Mon 3/21 13:50:12.111 [Fork-OPUS4-111999@14964a1] STARTING background video thumb preloader thread, ID = 0.9563207565854419
Mon 3/21 13:50:12.116 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ThumbShadow.png
Mon 3/21 13:50:12.120 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=254 h=254
Mon 3/21 13:50:12.122 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 295x442 for .\userdata\Phoenix\cache\imagetrans\PCwq\ca22476e71edab7df19aedb5f3d6ae01.jpg fileSize=38815
Mon 3/21 13:50:12.133 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file .\userdata\Phoenix\cache\imagetrans\PCwq\ca22476e71edab7df19aedb5f3d6ae01.jpg
Mon 3/21 13:50:12.140 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=295 h=442
Mon 3/21 13:50:12.143 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 40x651 for C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVBG.png fileSize=918
Mon 3/21 13:50:12.149 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVBG.png
Mon 3/21 13:50:12.152 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=40 h=651
Mon 3/21 13:50:12.153 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 31x28 for C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVUp.png fileSize=1440
Mon 3/21 13:50:12.158 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVUp.png
Mon 3/21 13:50:12.160 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=31 h=28
Mon 3/21 13:50:12.161 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 31x28 for C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVDown.png fileSize=1496
Mon 3/21 13:50:12.166 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVDown.png
Mon 3/21 13:50:12.168 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=31 h=28
Mon 3/21 13:50:12.169 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 29x576 for C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVArea.png fileSize=1065
Mon 3/21 13:50:12.174 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVArea.png
Mon 3/21 13:50:12.176 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=29 h=576
Mon 3/21 13:50:12.177 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading RawImage of size 18x40 for C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVBar.png fileSize=741
Mon 3/21 13:50:12.183 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Loading 0x0 image from file C:\Program Files (x86)\SageTV\SageTV\STVs\SageTV7\Themes\Standard\ScrollVBar.png
Mon 3/21 13:50:12.184 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=18 h=40
Mon 3/21 13:50:14.851 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating new RawImage for font rendering w=128 h=128
Mon 3/21 13:50:14.856 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Rendered new font to raw cache index=105 font=MetaFont[fonts\DejaVuSans, size=20, style=0, height=23.0, ascent=19.0, descent=5.0, leading=-1.0, class=class sage.FreetypeFont]
Mon 3/21 13:50:14.863 [FinalRender-SAGETV_PROCESS_LOCAL_UI@13256d0] Creating DirectX9 Texture from nio buffer w=128 h=128
Mon 3/21 13:50:16.816 [BGLoader2-SAGETV_PROCESS_LOCAL_UI@591e59] Loading RawImage of size 375x370 for G:\Videos\Chipper - Into the Great Outdoors\folder.jpg fileSize=43302
Mon 3/21 13:50:16.848 [BGLoader2-SAGETV_PROCESS_LOCAL_UI@591e59] Loading 0x0 image from file G:\Videos\Chipper - Into the Great Outdoors\folder.jpg
Mon 3/21 13:50:16.852 [Fork-OPUS4-111999@14964a1] Creating DirectX9 Texture from nio buffer w=16 h=16
Mon 3/21 13:50:16.860 [BGLoader2-SAGETV_PROCESS_LOCAL_UI@591e59] Creating DirectX9 Texture from nio buffer w=375 h=370
                                                                                Mon 3/21 13:50:25.828 [Fork-BASE-55376@133ad1] Updating Disk Space Bar

**Comment by ddoell** [comment]
It doesn't look like I got the error. Maybe I spent to much time figuring out how to copy out of that DOS window. I started over and this time I copied everything right away into a Word file. I got 18 pages and I  think I see the errors you pointed out. Do you want me to upload the Word file or paste directly in the website?

**Comment by Narflex** [comment]
Just upload the file.

Jeff Kardatzke

**Comment by ddoell** [comment]
[Doell Console.docx](https://github.com/google/sagetv/files/182944/Doell.Console.docx)

See if this is what you need. Dave

**Comment by Narflex** [comment]
OK, now I see the bug. :-) I'll fix it later this week....I'm at an airport
right now.

Jeff Kardatzke

**Comment by ddoell** [comment]
Okay....thanks for all the time you've spent. I was just thinking it's been about 6 or 7 years since the first time you helped me with a Sage problem on the forum. And like it did back then it still blows me away how hands on you are with your customers.....even though I guess I'm not technically a customer anymore:-). I really appreciate it. Dave

**Comment by Narflex** [comment]
Fixed and merged. :)

**Comment by ddoell** [comment]
Pardon my ignorance on the process....but does this mean that a fix for the sorting problem will be included in the next update of the v9 files? If so then once I download and install the updated files it should fix the sort of my DVD/BD videos?

**Comment by Narflex** [comment]
Yes, that's correct...either you need to build a new version yourself...or
wait for someone else to do it (which I know is done pretty regularly).

On Thu, Mar 24, 2016 at 7:09 PM, ddoell <notifications@github.com> wrote:

> Pardon my ignorance on the process....but does this mean that a fix for
> the sorting problem will be included in the next update of the v9 files? If
> so then once I download and install the updated files it should fix the
> sort of my DVD/BD videos?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/89#issuecomment-201108521>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.
