### ISSUE TITLE
Houston channels limited guide data

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#91]
I only have a few hours of guide data for Houston channels KRIV 26.1 and KTRK 13.1. I am using Zap2it guide data. Are these channels not included in the Zap2it guide data?

**Comment by Narflex** [comment]
Look at the detailed info for a program on those channels, and look at the
ShowID. If it starts with DT then these are not from Tribune and that would
explain it.

Jeff Kardatzke

**Comment by 49studebaker** [comment]
The ShowID starts with DT. That explains why these channels have limited guide data.
